### ISSUE TITLE
Handle OpenShift resources

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/SaaSi#9]
OpenShift resources like the `Route`s are managed as generic resources from which the original Namespace setting is removed:
we should handle it appropriately instead and remove the Namespace field in a more appropriate way

**Comment by zvigrinberg** [comment]
@dmartinol Can you be more specific with an example?
If i understood correctly,  your intention is that namespace fielld can't be removed from openshift' resources , then we can handle it using the following approach:

We can use kustomize, to definine dummy open api openshift resources definition, and then delete the namespace from resources using kustomize, i have an example for how to do it.

We need to do it because k8 support patching resources using json patching(using operation and json path)only for resources that it knows and , even there, the paths that are supported are limited, and that's why probably it doesn't happen automatically on the normal path.

In this case, kustomize can comes to the rescue with introducing dummy openapi definitions for openshift resources(for route, deploymentconfig,buildconfig, etc).

**Comment by dmartinol** [comment]
The point was specific to the implementation at:
https://github.com/RHEcosystemAppEng/SaaSi/blob/77ee6cfa1e4417a6bd3704ba4613d2ff0325c10c/replica-builder/install-builder/pkg/installer/parametrizer.go#L52

Here we use a generic decoder for the extracted YAML files, but this has no registered schemas for OpenShift resources and also for others like:

apiVersion: authorization.openshift.io/v1
kind: RoleBinding

Because of that we added a specific code to clear the namespace field in the YAML file itself, instead of updating the related K8s/OpenShift resource. It would be better to have a unique approach instead: what you show with the kustomize patch is also fine but needs to be applied on all the relevant resources, not just the OpenShift ones.
